ACTION_MAP = {
    # --- 基础指令 ---小右转-镜像版2
    "wtest":  ("向前慢走1步官方版随意测试.json",  "wtest",  ""),
    "box_turnright_q_v1":    ("box_turnright_q_v1.json",  "req",  ""),
    "forward_q":     ("向前快走3步官方版.json",  "wq",  ""),
    "forward_q_10":     ("向前快走3步-后仰10平手.json",  "wqh10",  ""),
    "forward_guan":     ("向前慢走1步官方版.json",  "wguan",  ""),
    "forward":     ("forward1step.json",  "w",  ""),
    "forward_s":     ("向前走2cm-稳定.json",  "ws",  ""),
    "back":     ("FastSmoothBackward2s.json", "s", ""),
    "back_s":     ("向后走2cm-稳定.json",  "ss",  ""),
    "forward_q":     ("向前慢走1步官方版加速.json",  "wjia",  ""),
    "forward_1_step":     ("forward1step.json",  "wt",  ""),
    "back_2_step":        ("FastSmoothBackward2s.json",  "s",  ""),
    "left":          ("向左平移1步官方版.json",  "a",  ""),
    "right":         ("向右平移1步官方版.json",  "d",  ""),
    "turnleft":       ("leftturn1s.json",  "q",  ""),
    "turnright":      ("rightturn1s.json",  "e",  ""),
    "left_s":     ("小左移.json",  "as",  ""),
    "right_s":     ("小右移.json",  "ds",  ""),
    "turnleft_s":     ("小左转.json",  "qs",  ""),
    "turnright_s":     ("小右转-镜像版2.json",  "es",  ""),
    "pick_cube_old":          ("配送-抱快递-夹得超紧.json",  "f_old",  ""),
    "pick_cube":     ("抱起快递tv版3.json",  "f",  ""),
    "put_cube":    ("配送-放快递.json",  "rf",  ""),
    "put_cube_down":   ("putcubedown.json",  "rf2",  ""),
    "pick_object":     ("pick.json",  "g",  ""),
    "giveup_cube":     ("release.json",  "rg",  ""),
    "reset_stand":     ("stand.json",  "c",  ""),
    "up_stair":    ("无用-test上楼梯3.json",  "ri",  ""),
    "push_rag":   ("推抹布-贴胸准高慢延-11次.json",  "p11",  ""),
    "push_rag1":   ("推抹布-贴胸准高慢延-开始.json",  "p1",  ""),
    "push_rag2":   ("推抹布-贴胸准高慢延-右移.json",  "p2",  ""),
    "push_rag3":   ("推抹布-贴胸准高慢延-结束.json",  "p3",  ""),
    "squat":    ("squat.json",  "cx",  ""),
    "back_up":   ("standupfaceup.json",  "backup",  ""),
    "forward_up":   ("前倒地起身-超级自编完整版.json",  "forwardup",  ""),
    "stand_up_face_down":   ("standupfacedown.json",  "forwardupbad",  ""),
    "box_left":    ("抱快递左移.json",  "ra",  ""),
    "box_right":    ("抱快递右移.json",  "rd",  ""),
    "box_forward":     ("boxforward1s.json",  "rw",  ""),
    
    "box_forward_s_bad":    ("box_forward_s_v3.json",  "rws_bad",  ""),
    "box_back":    ("BoxBack2.json",  "rs",  ""),
    
    "box_back_s":    ("向后走2cm-稳定-抱箱.json",  "rss",  ""),
    "box_turnleft":   ("BoxLeftTurn1s.json",  "rq",  ""),
    "box_turnright":  ("BoxRightTurn1s.json",  "re",  ""), #BoxRightTurn1s.json
    "put_box_level1":    ("书架-放一层.json",  "ro1",  ""),
    "put_box_level2":    ("书架-放二层3.json",  "ro2",  ""),
    "轻微后仰看字牌":    ("轻微后仰看字牌.json",  "lean",  ""),
    "下楼梯1厘米-修正版":    ("下楼梯1厘米-修正版.json",  "k",  ""),

    # --- 扩展指令 ---
    "stand":   ("stand.json",  "ic",  ""),
    "move_left_ext":   ("move_left.json",  "ia",  ""),
    "move_right_ext":     ("move_right.json",  "id",  ""),
    "hug_1":   ("hug_1.json",  "if",  ""),
    "hug_2":   ("hug_2.json",  "ird",  ""),
    "hug_3":   ("hug_3.json",  "irf",  ""),
    "pick_1":   ("pick_1.json",  "ip",  ""),
    "pick_back":   ("pick_back.json",  "irs",  ""),
    "pick_f":   ("pick_f.json",  "irw",  ""),
    "wanyao":   ("wanyao.json",  "iwanyao",  ""),
    "pick_stairs_up":  ("pick_stairs_up.json",  "iri",  ""),
    "pick_stairs_up_1": ("pick_stairs_up_1.json",  "iri1",  ""),  #这个动作是能抱箱子上楼梯的
    "pick_stairs_down_1": ("pick_stairs_up.json",  "irk",  ""),
    "pick_stairs_down_2": ("pick_stairs_down_2.json",  "irk2",  ""),
    "pick_p":   ("pick_p.json",  "irf",  ""),
    "ick_m_l":  ("pick_m_l.json",  "irl",  ""),
    "pick_m_r":  ("pick_m_r.json",  "ird",  ""),
    "turnleft_ss":  ("ml_1.json",  "iq",  ""),
    "turnright_ss":  ("mr_1.json",  "ie",  ""),
    "ml_x":  ("ml_x.json",  "ia",  ""),
    "mr_x":  ("mr_x.json",  "id",  ""),
    "box_turnleft_s":  ("pick_l_x.json",  "irq",  ""),
    "box_turnright_s":  ("pick_r_x.json",  "ire",  ""),
    "pick_m_l_x": ("pick_m_l_x.json",  "ird",  ""),
    "pick_m_r_x": ("pick_m_r_x.json",  "ira",  ""),
    "pick_f_x":  ("pick_f_x.json",  "irdw",  ""),
    "box_right_forward_s":  ("box_forward_s_pickfx.json",  "rws",  ""),
}

# 修改上述，要求导入action_map.py